name: llm-env
channels:
  - pytorch
  - nvidia
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.13.1
  - torchvision=0.14.1
  - torchaudio=0.13.1
  - pytorch-cuda=11.7
  - cudatoolkit=11.7
  - pip
  - pip:
    - transformers==4.31.0
    - accelerate==0.21.0
    - scipy==1.10.1
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - pytorch-lightning==2.0.2
    - sentencepiece==0.1.99
    - protobuf==3.20.3
    - tokenizers==0.13.3
    - einops==0.6.1
    - safetensors==0.3.1
    - packaging==23.1
    - ninja==1.11.1
    - datasets==2.13.0
    - peft==0.4.0
    - wandb==0.15.3
    - tqdm==4.65.0 