quantization:
  enabled: false
  precision: "int8"
  compute_dtype: "float16"

lora:
  enabled: false
  r: 8
  alpha: 32
  dropout: 0.05
  target_modules: ["q_proj", "v_proj"]

memory_efficient:
  gradient_checkpointing: false
  cpu_offload: false 