name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
save_path: "../../models"
force_download: false
cache:
  enabled: true
  max_memory: "16GiB"
model_settings:
  torch_dtype: "float16"
  device_map: "auto"
  low_cpu_mem_usage: true
chat_settings:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 1024
  stop_sequences: ["</s>", "<|user|>"]
  language: "korean"
  system_messages:
    korean: "당신은 한국어에 특화된 AI assistant 입니다. 친절하고 전문적으로 한국어로 답변해주세요."
    english: "You are a Korean-specialized AI assistant. Please respond in English." 