name: "upstage/SOLAR-10.7B-v1.0"
save_path: "../../models"
force_download: false
cache:
  enabled: true
  max_memory: "16GiB"
chat_settings:
  temperature: 0.7
  top_p: 0.9
  max_tokens: 1024
  stop_sequences: ["</s>", "<|user|>"]
  language: "korean"
  system_messages:
    korean: "당신은 AI assistant 입니다. 친절하고 전문적인 AI 어시스턴트로서 한국어로 답변해주세요."
    english: "You are an AI assistant. Please respond in English." 