prompt: "Please analyze the emotion in the following text:"
format_instruction: |
  Respond in this exact JSON format:
  {
    "emotion": "happy/angry/neutral",
    "confidence": 0.0-1.0,
    "reason": "your explanation",
    "keywords": ["word1", "word2"]
  }
template: "{prompt}\n\n{format_instruction}\n\nText: {text}"
batch_settings:
  max_batch_size: 8
  parallel_processing: true
generation:
  temperature: 0.1
  max_tokens: 100 