# 태스크 설정
task_type: "emotion"  # query, summary, emotion 중 선택
debug:
  enabled: false

# 모델 설정
model:
  name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"  #"  "meta-llama/Meta-Llama-3-8B" # lzw1008/Emollama-7b" #  " #"ZebangCheng/Emotion-LLaMA" ## "sebdg/llama3-8b-emotions" #  ahmedeltabakh/emotions-classification-18-llama-2-7b #
  # ZebangCheng/Emotion-LLaMA 
  #name: "meta-llama/Llama-2-7b-chat-hf"  # 모델 이름 수정
  save_path: "../../models"  # 모델 저장 경로
  force_download: false  # 기존 캐시 무시하고 강제 다운로드 여부
  cache:
    enabled: true  # 캐시 사용 여부
    max_memory: "8GiB"  # 최대 메모리 사용량

#"mrm8488/t5-base-finetuned-emotion" 

project:
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
# 기본 설정
seed: 42
max_new_tokens: 2048

# Tasks configuration
tasks:
  emotion:
    prompt: "Please analyze the emotion in the following text:"
    format_instruction: |
      Respond in this exact JSON format:
      {
        "emotion": "neutral/happy/sad/angry/fear/surprise/disgust",
        "confidence": 0.0-1.0,
        "reason": "your explanation",
        "keywords": ["word1", "word2"]
      }
    template: "{prompt}\n\n{format_instruction}\n\nText: {text}"
    generation:
      temperature: 0.1
      max_tokens: 100
  
  summary:
    template:
      korean: "다음 텍스트를 논리적 순서로 요약해주세요. 중복은 제거하고, 마크다운 형식으로 2-3단계 헤딩과 들여쓰기를 사용해주세요:\n{text}"
      english: "Please summarize the following text in logical order. Remove duplicates. Use markdown format with level 2-3 headings and 2-3 level indentation:\n{text}"
    generation:
      temperature: 0.3
      max_tokens: 2048
  
  chat:
    system_prompt:
      korean: "당신은 친절한 AI 어시스턴트입니다. 한국어로 간단명료하게 답변해주세요."
      english: "You are a friendly AI assistant. Please provide concise responses in English."
    concise_instruction:
      korean: "답변은 간단명료하게 해주세요."
      english: "Please keep responses concise."
    exit_keywords: 
      korean: ["quit", "exit", "bye"]
      english: ["quit", "exit", "bye"]
    max_history: 10
    generation:
      temperature: 0.7
      max_tokens: 1024

# Common generation settings
generation:
  top_p: 0.9
  top_k: 10

# Quantization settings
quantization:
  enabled: true
  precision: "int4"
  compute_dtype: "float16"

# 언어 설정
language: "english"  # korean 또는 english

# 프롬프트 설정
prompt:
  korean: "당신은 유능한 AI 감정 분석가입니다. 모든 질문에 대해 반드시 한국어로만 답변해주세요. 응답은 반드시 지정된 JSON 형식을 정확히 따라야 합니다."
  english: "You are an expert emotion analyzer. Please answer all questions in English only. Your response must strictly follow the specified JSON format. Do not include any text outside the JSON structure."

# 생성 설정 추가
generation:
  temperature:
    emotion: 0.1
    default: 0.3
  max_tokens:
    emotion: 10
    default: 2048
  top_p: 0.9
  top_k: 10

# 입력 설정
input_file: "samples/quote.txt"  # 기본 입력 파일 경로

# 배치 처리 설정
batch_processing:
  input_dir: null #"samples/texts"  # txt 파일들이 있는 디렉토리
  csv_file: "samples/data.csv"  # CSV 파일 경로
  text_column: "text"  # CSV에서 처리할 텍스트 컬럼명
  batch_size: 4  # 한 번에 처리할 파일/행 수