# 태스크 설정
task_type: "emotion"  # query, summary, emotion 중 선택

# 모델 설정
model:
  name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
  save_path: "../../models"
  force_download: false
  cache:
    enabled: true
    max_memory: "8GiB"  # 최대 메모리 사용량

project:
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
# 기본 설정
seed: 42
max_new_tokens: 2048

# 양자화 설정
quantization:
  enabled: true
  precision: "int8"
  compute_dtype: "float16"

# 언어 설정
language: "english"  # korean 또는 english

# 프롬프트 설정
prompt:
  korean: "당신은 유능한 AI 어시스턴트입니다. 모든 질문에 대해 반드시 한국어로만 답변해주세요."
  english: "You are a helpful AI assistant. Please answer all questions in English only."

# 생성 설정 추가
generation:
  temperature:
    emotion: 0.1
    default: 0.3
  max_tokens:
    emotion: 10
    default: 2048
  top_p: 0.9
  top_k: 10

# 입력 설정
input_file: "samples/quote.txt"  # 기본 입력 파일 경로

# 배치 처리 설정
batch_processing:
  input_dir: "samples/texts"  # txt 파일들이 있는 디렉토리
  csv_file: "samples/data.csv"  # CSV 파일 경로
  text_column: "text"  # CSV에서 처리할 텍스트 컬럼명
  batch_size: 4  # 한 번에 처리할 파일/행 수