defaults:
  - model: llama_blossom
  - task: summary
  - optimization: default
  - _self_

seed: 42
max_new_tokens: 2048
task_type: "summary"

generation:
  top_p: 0.9
  top_k: 10

prompt: "You are a helpful AI assistant specialized in text analysis and emotional understanding. Please provide detailed and accurate responses."