# 모델 설정
model:
  name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
  save_path: "../../models"
  force_download: false

project:
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}
# 기본 설정
seed: 42
max_new_tokens: 2048

# 양자화 설정
quantization: true
precision: "int8"

# 태스크 설정
task_type: "summary"  # query, summary, emotion 중 선택

# 프롬프트 설정
prompt_template: "{domain}에서 가장 중요한 것, 그 이유는?"
domain: "인공지능"
prompt: "You are a helpful AI assistant. Please answer the user's questions kindly. 당신은 유능한 AI 어시스턴트 입니다. 사용자의 질문에 대해 친절하게 답변해주세요."

# 템플릿 설정
summary_template: "다음 텍스트를 논리적 흐름 순으로 정리 요약. 중복은 제거. 형식은 마크다운, 2-3 단계 헤딩 및 2-3 단계 - 들여쓰기:\n{text}"
emotion_template: "다음 텍스트의 감정을 'happy', 'angry', 'neutral' 중 하나로만 답해주세요:\n{text}"