# Task settings
task_type: "emotion"  # Choose from: query, summary, emotion
debug:
  enabled: false

# Model settings
model:
  name: "MLP-KTLim/llama-3-Korean-Bllossom-8B"
  save_path: "../../models"  # Model save path
  force_download: false  # Force download ignoring cache
  cache:
    enabled: true  # Use cache
    max_memory: "8GiB"  # Maximum memory usage

# Project settings
project:
  timestamp: ${now:%Y%m%d_%H%M%S}
  hydra_cwd: ${hydra:runtime.cwd}

# Basic settings
seed: 42
max_new_tokens: 2048
 
# Quantization settings
quantization:
  enabled: true
  precision: "int4"
  compute_dtype: "float16"

# Language settings
language: "english"  # korean or english

# Prompt settings
prompt:
  korean: "You are a skilled AI emotion analyzer. Please respond in Korean only. Your response must strictly follow the specified JSON format."
  english: "You are an expert emotion analyzer. Please answer all questions in English only. Your response must strictly follow the specified JSON format. Do not include any text outside the JSON structure."

# Generation settings
generation:
  temperature:
    emotion: 0.1
    default: 0.3
  max_tokens:
    emotion: 10
    default: 2048
  top_p: 0.9
  top_k: 10

# Input settings
input_file: "samples/quote.txt"  # Default input file path

# Batch processing settings
batch_processing:
  input_dir: null  # Directory containing txt files
  csv_file: "samples/VA.csv"  # CSV file path

  text_column: "text"  # Text column name in CSV
  batch_size: 4  # Number of files/rows to process at once